# /etc/bash/bashrc

if [ -e /etc/profile ]; then
    . /etc/profile
fi

if [ -v "$(command -v shopt)" ]; then
    shopt -s checkwinsize
    shopt -s no_empty_cmd_completion
    shopt -s histappend
fi

if [ -f ~/.profile ]; then
    . ~/.profile
fi

unset sh
