#!/usr/bin/env sh

PATH="/sbin:/usr/sbin:/opt/sbin:/usr/local/sbin/"
PATH="$PATH:/bin:/usr/bin:/opt/bin:/usr/local/bin"
PATH="$PATH:$HOME/bin:$HOME/.local/bin"

MANPATH="/usr/man:/usr/share/man:/usr/local/man:/usr/local/share/man"
MANPATH="$MANPATH:$HOME/man:$HOME/.local/man:$HOME/.local/share/man"

export PATH MANPATH

if [ -d "$HOME"/.profile.d ]; then
    for i in "$HOME"/.profile.d/*.sh; do
        if [ -r "$i" ]; then
	    . "$i"
	fi
    done

    unset i
fi
