#!/usr/bin/env sh

# Load global profile
if [ -f /etc/profile ]; then
    . /etc/profile
fi

# Load local profile.d scripts
if [ -d "$HOME"/.profile.d ]; then
    for script in "$HOME"/.profile.d/*.sh; do
        if [ -r "$script" ]; then
            . "$script"
        fi
    done

    unset script
fi
