#!/usr/bin/env sh

# Ensure ~/.profile is loaded
export ENV="$HOME/.profile"

# Pretend we're using Gnome for themes
export DESKTOP_SESSION=gnome

# Set screen brightness to 20%
xbacklight -set 20%

# Hide mouse cursor when inactive
if [ -x "$(command -v unclutter)" ]; then
	unclutter -idle 2 -noevents -root &
fi

# Mute master audio output channels
mixerctl outputs.master=0
mixerctl outputs.master.mute=on

# Mute master audio input channels
mixerctl record.volume=0
mixerctl record.volume.mute=on

# Start dbus
if [ -x /usr/local/bin/dbus-launch -a -z "${DBUS_SESSION_BUS_ADDRESS}" ]; then
	eval `dbus-launch --sh-syntax --exit-with-x11`
fi

# Start i3
if [ -x "$(command -v i3)" ]; then
	i3
fi
